### ISSUE TITLE
Add hash @key support inside #each block

### ISSUE THREAD

**Issue by andrhamm** [FlavourSaver/FlavourSaver#17]
Currently will get `FlavourSaver::UndefinedPrivateVariableException (private variable not found @key):` when trying to access the index/key of the current item while inside an `each` loop. Doesn't look like these "helpers" are supported.

Discussion where the support is added to handlebarsjs: https://github.com/wycats/handlebars.js/issues/250#issuecomment-9514811

Example JS usage:
http://jsfiddle.net/wMmHS/69/

Example template for hash:

```
<table>
  <tr>
    <th>key</th>
    <th>value</th>
  </tr>
  {{#each obj}}
  <tr>
    <td>{{@key}}:</td>
    <td>{{this}}</td>
  </tr>
  {{/each}}
</table>
```

**Comment by grumbleafrican** [comment]
```
irb(main):001:0> x = {a: 'av', c: 'de'}
=> {:a=>"av", :c=>"de"}
irb(main):002:0> x.each {|element| puts element.inspect}
[:a, "av"]
[:c, "de"]
```

What is the expected behavior? 


If hash, the `@key` is set, and:
1)  the element is an array consisting of a key-value pair, or
2) the element is just the value?

(2) seem cleaner, but will break backward compatibility for existing users.

if array, the `@key` is set to
1) the index? (0..n), or
2) nil

**Comment by andrhamm** [comment]
`@key` should only be supported when iterating on an object, since it is equiv of `@index` for arrays.

For expected behavior, see [this comment](https://github.com/wycats/handlebars.js/issues/250#issuecomment-17497729) on the linked issue.
